### ISSUE TITLE
Your version of json.hpp does not compile with clang 4.0

### ISSUE THREAD

**Issue by mdr1384** [pokowaka/jwt-cpp#11]
Your "json.hpp" file is supposedly v2.1.1 from [nlohmann/json](https://github.com/nlohmann/json/tree/v2.1.1) but it has massive differences from the actual version. It almost looks like some kind of weird pre-processing was done on it. Anyway, there are many cases of `std::numeric_limits<type>::(xxx)()` which does not compile with clang 4.0. The original v2.1.1 json.hpp file has this `std::numeric_limits<type>::xxx()` which compiles fine.

Error with clang 4.0:
```
z.cc:5:44: error: expected unqualified-id
    std::cout << std::numeric_limits<int>::(max)() << std::endl;
                                           ^
z.cc:5:45: error: use of undeclared identifier 'max'; did you mean 'std::max'?
```
I was able to replace your version of the file with the unaltered one and get it to compile, but I am not sure what other mods you might have made that are necessary for correct operation (hopefully none -- in which case I suggest either including the unaltered version, or removing it and adding a dependency on nlohmann/json.)

**Comment by faragon** [comment]
It fails also with GCC 5.4 (Ubuntu 16.04) and GCC 7 (Ubuntu 17.10), with similar error.

**Comment by DanFTRX** [comment]
It seems my last PR (https://github.com/pokowaka/jwt-cpp/commit/5a267d13179cbc1627c6b6188d4181b86b6e4518) did the preprocessor macro expansions escapes incorrectly, it should be (std::numeric_limits<size_t>::max) rather than std::numeric_limits<size_t>::(max).     I should have noticed the difference when I brought up the reference change in nlohmann/json 3.0 (https://github.com/nlohmann/json/commit/95474e420de25ec7db4875e889201229820ef564)

**Comment by mdr1384** [comment]
FYI - we successfully removed your json.hpp file and added a dependency on the devel/nlohmann-json FreeBSD port and your library built fine and passed all self tests.

**Comment by logixworx** [comment]
Still fails here too. Fix?

**Comment by pokowaka** [comment]
I should probably add a subtree dependency on the Json lib.

**Comment by pokowaka** [comment]
We now have a travis build for clang 5, which succeeds.
